sudo: required

services:
  - docker

before_install:
  - mkdir -p ./test/results
  - docker-compose -f docker-compose.test.yml build sut

script:
  - docker-compose -f docker-compose.test.yml run sut

